openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            common.*: Grant all COMMON actions

tags:
  - name: Places
    description: |
      These APIs gives the places suggestions and geographic data of a place.
  - name: Data Extraction
    description: |
      These APIs gives the expense relevant data from the reciepts

paths:
  /v4/common/places:
    $ref: 'paths/places.yaml'
  /v4/common/places/{id}:
    $ref: 'paths/places@{id}.yaml'
  /v4/common/vision_audits/{id}:
    $ref: 'paths/vision_audits@{id}.yaml'
  /v4/fyler/vision_extract:
    $ref: 'paths/vision_extract.yaml'
