openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            common.*: Grant all COMMON actions

tags:
  - name: Data Extraction
    description: |
      These APIs gives you the expense relevant data from the reciepts.

paths:
  /v4/common/vision_audits/{audit_id}:
    $ref: 'paths/vision_audits.yaml'
  /v4/fyler/vision_extract:
    $ref: 'paths/vision_extract.yaml'